/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DetectedObject } from "./DetectedObject";
import { DetectedObjectCountArgs } from "./DetectedObjectCountArgs";
import { DetectedObjectFindManyArgs } from "./DetectedObjectFindManyArgs";
import { DetectedObjectFindUniqueArgs } from "./DetectedObjectFindUniqueArgs";
import { CreateDetectedObjectArgs } from "./CreateDetectedObjectArgs";
import { UpdateDetectedObjectArgs } from "./UpdateDetectedObjectArgs";
import { DeleteDetectedObjectArgs } from "./DeleteDetectedObjectArgs";
import { ImageFindManyArgs } from "../../image/base/ImageFindManyArgs";
import { Image } from "../../image/base/Image";
import { DetectedObjectService } from "../detectedObject.service";
@graphql.Resolver(() => DetectedObject)
export class DetectedObjectResolverBase {
  constructor(protected readonly service: DetectedObjectService) {}

  async _detectedObjectsMeta(
    @graphql.Args() args: DetectedObjectCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DetectedObject])
  async detectedObjects(
    @graphql.Args() args: DetectedObjectFindManyArgs
  ): Promise<DetectedObject[]> {
    return this.service.detectedObjects(args);
  }

  @graphql.Query(() => DetectedObject, { nullable: true })
  async detectedObject(
    @graphql.Args() args: DetectedObjectFindUniqueArgs
  ): Promise<DetectedObject | null> {
    const result = await this.service.detectedObject(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DetectedObject)
  async createDetectedObject(
    @graphql.Args() args: CreateDetectedObjectArgs
  ): Promise<DetectedObject> {
    return await this.service.createDetectedObject({
      ...args,
      data: {
        ...args.data,

        image: args.data.image
          ? {
              connect: args.data.image,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => DetectedObject)
  async updateDetectedObject(
    @graphql.Args() args: UpdateDetectedObjectArgs
  ): Promise<DetectedObject | null> {
    try {
      return await this.service.updateDetectedObject({
        ...args,
        data: {
          ...args.data,

          image: args.data.image
            ? {
                connect: args.data.image,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DetectedObject)
  async deleteDetectedObject(
    @graphql.Args() args: DeleteDetectedObjectArgs
  ): Promise<DetectedObject | null> {
    try {
      return await this.service.deleteDetectedObject(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Image], { name: "images" })
  async findImages(
    @graphql.Parent() parent: DetectedObject,
    @graphql.Args() args: ImageFindManyArgs
  ): Promise<Image[]> {
    const results = await this.service.findImages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Image, {
    nullable: true,
    name: "image",
  })
  async getImage(
    @graphql.Parent() parent: DetectedObject
  ): Promise<Image | null> {
    const result = await this.service.getImage(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
