/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ImageService } from "../image.service";
import { ImageCreateInput } from "./ImageCreateInput";
import { Image } from "./Image";
import { ImageFindManyArgs } from "./ImageFindManyArgs";
import { ImageWhereUniqueInput } from "./ImageWhereUniqueInput";
import { ImageUpdateInput } from "./ImageUpdateInput";
import { DetectedObjectFindManyArgs } from "../../detectedObject/base/DetectedObjectFindManyArgs";
import { DetectedObject } from "../../detectedObject/base/DetectedObject";
import { DetectedObjectWhereUniqueInput } from "../../detectedObject/base/DetectedObjectWhereUniqueInput";
import { ObjectCountFindManyArgs } from "../../objectCount/base/ObjectCountFindManyArgs";
import { ObjectCount } from "../../objectCount/base/ObjectCount";
import { ObjectCountWhereUniqueInput } from "../../objectCount/base/ObjectCountWhereUniqueInput";

export class ImageControllerBase {
  constructor(protected readonly service: ImageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Image })
  async createImage(@common.Body() data: ImageCreateInput): Promise<Image> {
    return await this.service.createImage({
      data: {
        ...data,

        detectedObject: data.detectedObject
          ? {
              connect: data.detectedObject,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,

        detectedObject: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Image] })
  @ApiNestedQuery(ImageFindManyArgs)
  async images(@common.Req() request: Request): Promise<Image[]> {
    const args = plainToClass(ImageFindManyArgs, request.query);
    return this.service.images({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,

        detectedObject: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Image })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async image(
    @common.Param() params: ImageWhereUniqueInput
  ): Promise<Image | null> {
    const result = await this.service.image({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,

        detectedObject: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Image })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateImage(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() data: ImageUpdateInput
  ): Promise<Image | null> {
    try {
      return await this.service.updateImage({
        where: params,
        data: {
          ...data,

          detectedObject: data.detectedObject
            ? {
                connect: data.detectedObject,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          url: true,

          detectedObject: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Image })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteImage(
    @common.Param() params: ImageWhereUniqueInput
  ): Promise<Image | null> {
    try {
      return await this.service.deleteImage({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          url: true,

          detectedObject: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/detectedObjects")
  @ApiNestedQuery(DetectedObjectFindManyArgs)
  async findDetectedObjects(
    @common.Req() request: Request,
    @common.Param() params: ImageWhereUniqueInput
  ): Promise<DetectedObject[]> {
    const query = plainToClass(DetectedObjectFindManyArgs, request.query);
    const results = await this.service.findDetectedObjects(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        confidenceScore: true,
        boundingBox: true,

        image: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/detectedObjects")
  async connectDetectedObjects(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() body: DetectedObjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      detectedObjects: {
        connect: body,
      },
    };
    await this.service.updateImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/detectedObjects")
  async updateDetectedObjects(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() body: DetectedObjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      detectedObjects: {
        set: body,
      },
    };
    await this.service.updateImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/detectedObjects")
  async disconnectDetectedObjects(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() body: DetectedObjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      detectedObjects: {
        disconnect: body,
      },
    };
    await this.service.updateImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/objectCounts")
  @ApiNestedQuery(ObjectCountFindManyArgs)
  async findObjectCounts(
    @common.Req() request: Request,
    @common.Param() params: ImageWhereUniqueInput
  ): Promise<ObjectCount[]> {
    const query = plainToClass(ObjectCountFindManyArgs, request.query);
    const results = await this.service.findObjectCounts(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        objectName: true,
        count: true,

        image: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/objectCounts")
  async connectObjectCounts(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() body: ObjectCountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      objectCounts: {
        connect: body,
      },
    };
    await this.service.updateImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/objectCounts")
  async updateObjectCounts(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() body: ObjectCountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      objectCounts: {
        set: body,
      },
    };
    await this.service.updateImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/objectCounts")
  async disconnectObjectCounts(
    @common.Param() params: ImageWhereUniqueInput,
    @common.Body() body: ObjectCountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      objectCounts: {
        disconnect: body,
      },
    };
    await this.service.updateImage({
      where: params,
      data,
      select: { id: true },
    });
  }
}
